package de.oberamsystems.slm.model;

public enum BookGenreEnum {
	ACTION, BIOGRAPHY, CHILDREN, CRIME, ESSAY, FANTASY,
	FOODDRINK, GRAPHICNOVEL, GUIDE, HISTORICALFICTION, HISTORY, HORROR ,HUMANITIES,
	HUMOR, NEWADULT, PARENTING, PHILOSOPHICFICTION, PHOTOGRAPHY, RELIGION, ROMANCE,
	SCIENCE, SCIFI, SELFHELP, SHORTSTORY, THRILLER, TRAVEL, TRUECRIME, YOUNGADULT
}
