# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: ikalnytskyi/action-setup-postgres@v7
      id: postgres
      with:
        username: slm
        password: N0m1596.
        database: slm
    - run: ls
    - run: pwd
    - run: sudo chmod 0640  /home/runner/work/_temp/pgdata/pg_service.conf
    - run: sudo chown postgres  /home/runner/work/_temp/pgdata/pg_service.conf
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
    - name: cd in slm folder
      run: cd ..
    - name: checkout code
      run: git clone https://github.com/sidietz/slm.git
    - run: cd slm
    - env:
        PGSERVICE: "${{ steps.postgres.outputs.service-name }}"
      run: psql -c "ALTER USER slm WITH PASSWORD 'N0m1596.'"
    - env:
        PGSERVICE: "${{ steps.postgres.outputs.service-name }}"
        PGPASSWORD: N0m1596.
      run: PGPASSWORD=N0m1596. psql -h localhost -U slm -d slm -a -f slm/init.sql
    - name: Copy mail.properties
      run: cp slm/src/main/resources/default-mail.properties slm/src/main/resources/mail.properties
    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Build with Gradle 9.0
      run: cd slm && gradle build -S --debug

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        use-gradlew: false
        gradle-version: 9
